variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

stages:
  - build
  - upload

default:
  image: firexstuff/firex-alpine-build:3.9.10
  before_script:
    - python -m venv venv
    - source venv/bin/activate
    - pip install --upgrade pip
    - pip install --upgrade firexbuilder
    
build:
  stage: build
  script:
    - firex-build build
  artifacts:
    paths:
      - dist/
        
upload-pkg:
  stage: upload
  script: 
    - pip install keyrings.alt
    - firex-build upload_pip
  only:
    - tags
